name: webview_flutter_android
description: A Flutter plugin that provides a WebView widget on Android.
repository: https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
version: 3.7.0+4
publish_to: http://192.168.8.75:4000/

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: webview_flutter
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin
        dartPluginClass: AndroidWebViewPlatform

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.0
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  android_intent_plus:
    version: ^4.0.3+1
    hosted:
      name: android_intent_plus
      url: http://192.168.8.75:4000/
  webview_flutter_platform_interface:
    version: ^2.3.0+2
    hosted:
      name: webview_flutter_platform_interface
      url: http://192.168.8.75:4000/

dev_dependencies:
  build_runner: ^2.1.4
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  pigeon: ^9.2.4
